apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: democontainer
  name: democontainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: democontainer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: democontainer
    spec:
      containers:
      - image: mycontainer
        name: mycontainer
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo
  type: ClusterIP
status:
  loadBalancer: {}
